# An example of throwing exception
if __name__ == "__main__":
    x = [1,2,3]
    print(x[3])
